In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [7]:
df=pd.read_csv('/kaggle/input/datasets/brendan45774/test-file/tested.csv',usecols=['Age','Fare','Survived','SibSp','Parch'])

In [8]:
df.dropna(inplace=True)
df.shape

(331, 5)

In [10]:
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  34.5      0      0   7.8292
1         1  47.0      1      0   7.0000
2         0  62.0      0      0   9.6875
3         0  27.0      0      0   8.6625
4         1  22.0      1      1  12.2875

In [11]:
df['Family']=df['SibSp']+df['Parch']

In [12]:
df.head()

   Survived   Age  SibSp  Parch     Fare  Family
0         0  34.5      0      0   7.8292       0
1         1  47.0      1      0   7.0000       1
2         0  62.0      0      0   9.6875       0
3         0  27.0      0      0   8.6625       0
4         1  22.0      1      1  12.2875       2

In [13]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [14]:
df.head()

   Survived   Age     Fare  Family
0         0  34.5   7.8292       0
1         1  47.0   7.0000       1
2         0  62.0   9.6875       0
3         0  27.0   8.6625       0
4         1  22.0  12.2875       2

In [15]:
X=df.drop(columns=['Survived'])
y=df['Survived']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
X_train.head()

       Age     Fare  Family
281   0.75  13.7750       2
96   76.00  78.8500       1
341  32.00   7.5792       0
18   27.00   7.9250       1
26   22.00  61.9792       1

In [21]:
X_test.head()

      Age     Fare  Family
27   22.5   7.2250       0
389   6.0  21.0750       4
89    2.0  23.0000       2
280  23.0   8.6625       0
68   31.0  28.5375       0

In [17]:
clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print("Accuracy:",accuracy_score(y_pred,y_test))
print("Accuracy using cross validation:",np.mean(cross_val_score(clf,X,y,cv=10,scoring='accuracy')))

Accuracy: 0.582089552238806
Accuracy using cross validation: 0.5983957219251337

In [18]:
from sklearn.preprocessing import Binarizer

In [22]:
trf=ColumnTransformer([
    ('bin',Binarizer(copy=False),['Family'])
],remainder='passthrough')

In [23]:
X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.transform(X_test)

In [27]:
X_train_trf=pd.DataFrame(X_train_trf,columns=['family','Age','fare'])
X_test_trf=pd.DataFrame(X_test_trf,columns=['family','Age','fare'])

In [28]:
X_train_trf.head()

   family    Age     fare
0     1.0   0.75  13.7750
1     1.0  76.00  78.8500
2     0.0  32.00   7.5792
3     1.0  27.00   7.9250
4     1.0  22.00  61.9792

In [30]:
clf.fit(X_train_trf,y_train)
y_pred_trf=clf.predict(X_test_trf)
print("Accuracy:",accuracy_score(y_pred_trf,y_test))
X_trf=trf.fit_transform(X)
print("Accuracy using cross validation:",np.mean(cross_val_score(clf,X_trf,y,cv=10,scoring='accuracy')))

Accuracy: 0.5970149253731343
Accuracy using cross validation: 0.6072192513368984