In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [8]:
import pandas as pd

In [9]:
import requests

In [11]:
response=requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=ca392e8b6fc01949360506f927c2c466&language=en-US&page=1")

In [17]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 42.1605,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.717,
   'vote_count': 29989},
  {'adult': False,
   'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 36.5278,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.687,
   'vote_count': 22655},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 25.5386,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.572,
   'vote_count': 13718},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 23.5837,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.567,
   'vote_count': 17245},
  {'adult': False,
   'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 19.3006,
   'poster_path': '/2QXLVh32JKaWTjFJU3n8aIxRK9P.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.556,
   'vote_count': 9842},
  {'adult': False,
   'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
   'genre_ids': [35, 10749],
   'id': 1181678,
   'original_language': 'en',
   'original_title': '¿Quieres ser mi hijo?',
   'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
   'popularity': 7.9646,
   'poster_path': '/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg',
   'release_date': '2023-09-21',
   'title': '¿Quieres ser mi hijo?',
   'video': False,
   'vote_average': 8.546,
   'vote_count': 305},
  {'adult': False,
   'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 28.652,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.534,
   'vote_count': 18102},
  {'adult': False,
   'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 41.0006,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.527,
   'vote_count': 35382},
  {'adult': False,
   'backdrop_path': '/6N5d02quKqMKqvTpOdFmBDy9scY.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 11.6598,
   'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 4566},
  {'adult': False,
   'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 26.0735,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.505,
   'vote_count': 18991},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 35.04,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.495,
   'vote_count': 26226},
  {'adult': False,
   'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 31.5149,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.493,
   'vote_count': 20323},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 28.9398,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.486,
   'vote_count': 29882},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 24.26,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.478,
   'vote_count': 12372},
  {'adult': False,
   'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 48.8409,
   'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
   'release_date': '2014-11-05',
   'title': 'Interstellar',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 39210},
  {'adult': False,
   'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 23.996,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-23',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.467,
   'vote_count': 9505},
  {'adult': False,
   'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 26.916,
   'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.463,
   'vote_count': 29424},
  {'adult': False,
   'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 23.9359,
   'poster_path': '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.452,
   'vote_count': 14143},
  {'adult': False,
   'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 15.5611,
   'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.451,
   'vote_count': 4149},
  {'adult': False,
   'backdrop_path': '/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.0132,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.444,
   'vote_count': 6422}],
 'total_pages': 537,
 'total_results': 10727}

In [23]:
df=pd.DataFrame(response.json()['results'])

In [24]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,42.1605,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.717,29989
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",36.5278,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,22655
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,25.5386,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.572,13718
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,23.5837,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.567,17245
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,19.3006,/2QXLVh32JKaWTjFJU3n8aIxRK9P.jpg,1957-04-10,12 Angry Men,False,8.556,9842
5,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",7.9646,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,¿Quieres ser mi hijo?,False,8.546,305
6,False,/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",28.6520,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.534,18102
7,False,/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg,"[28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,41.0006,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.527,35382
8,False,/6N5d02quKqMKqvTpOdFmBDy9scY.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",11.6598,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.500,4566
9,False,/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,26.0735,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.505,18991
10,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,35.0400,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,The Lord of the Rings: The Return of the King,False,8.495,26226
11,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",31.5149,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.493,20323
12,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80, 35]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",28.9398,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,Pulp Fiction,False,8.486,29882
13,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,24.2600,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.478,12372
14,False,/2ssWTSVklAEc98frZUQhgtGHx7s.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,48.8409,/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg,2014-11-05,Interstellar,False,8.500,39210
15,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,23.9960,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-23,"The Good, the Bad and the Ugly",False,8.467,9505
16,False,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,26.9160,/saHP97rTPS5eLmrLQEcANmKrsFl.jpg,1994-06-23,Forrest Gump,False,8.463,29424
17,False,/gILte6Zd7m1YneIr6MVhh30S9pr.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",23.9359,/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg,1990-09-12,GoodFellas,False,8.452,14143
18,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,15.5611,/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg,1954-04-26,Seven Samurai,False,8.451,4149
19,False,/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0132,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.444,6422

In [25]:
df=pd.DataFrame(response.json()['results'])[['id','title','release_date','popularity','vote_average','vote_count','overview']]

In [26]:
df

,id,title,release_date,popularity,vote_average,vote_count,overview
0,278,The Shawshank Redemption,1994-09-23,42.1605,8.717,29989,Imprisoned in the 1940s for the double murder ...
1,238,The Godfather,1972-03-14,36.5278,8.687,22655,"Spanning the years 1945 to 1955, a chronicle o..."
2,240,The Godfather Part II,1974-12-20,25.5386,8.572,13718,In the continuing saga of the Corleone crime f...
3,424,Schindler's List,1993-12-15,23.5837,8.567,17245,The true story of how businessman Oskar Schind...
4,389,12 Angry Men,1957-04-10,19.3006,8.556,9842,The defense and the prosecution have rested an...
5,1181678,¿Quieres ser mi hijo?,2023-09-21,7.9646,8.546,305,"Lu, a conformist woman in her forties, learns ..."
6,129,Spirited Away,2001-07-20,28.6520,8.534,18102,"A young girl, Chihiro, becomes trapped in a st..."
7,155,The Dark Knight,2008-07-16,41.0006,8.527,35382,Batman raises the stakes in his war on crime. ...
8,19404,Dilwale Dulhania Le Jayenge,1995-10-20,11.6598,8.500,4566,"Raj is a rich, carefree, happy-go-lucky second..."
9,497,The Green Mile,1999-12-10,26.0735,8.505,18991,A supernatural tale set on death row in a Sout...
10,122,The Lord of the Rings: The Return of the King,2003-12-17,35.0400,8.495,26226,As armies mass for a final battle that will de...
11,496243,Parasite,2019-05-30,31.5149,8.493,20323,"All unemployed, Ki-taek's family takes peculia..."
12,680,Pulp Fiction,1994-09-10,28.9398,8.486,29882,"A burger-loving hit man, his philosophical par..."
13,372058,Your Name.,2016-08-26,24.2600,8.478,12372,High schoolers Mitsuha and Taki are complete s...
14,157336,Interstellar,2014-11-05,48.8409,8.500,39210,The adventures of a group of explorers who mak...
15,429,"The Good, the Bad and the Ugly",1966-12-23,23.9960,8.467,9505,While the Civil War rages on between the Union...
16,13,Forrest Gump,1994-06-23,26.9160,8.463,29424,A man with a low IQ has accomplished great thi...
17,769,GoodFellas,1990-09-12,23.9359,8.452,14143,"The true story of Henry Hill, a half-Irish, ha..."
18,346,Seven Samurai,1954-04-26,15.5611,8.451,4149,A samurai answers a village's request for prot...
19,12477,Grave of the Fireflies,1988-04-16,0.0132,8.444,6422,"In the final months of World War II, 14-year-o..."

In [29]:
df_movie=pd.DataFrame()

In [34]:
all_movies=[]

In [38]:
all_movies=[]
for i in range(1,501):
    response=requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=ca392e8b6fc01949360506f927c2c466&language=en-US&page={}".format(i))
    temp_df=pd.DataFrame(response.json()['results'])[['id','title','release_date','popularity','vote_average','vote_count','overview']]
    all_movies.append(temp_df)
    df_movie = pd.concat(all_movies, ignore_index=True)

In [40]:
df_movie

,id,title,release_date,popularity,vote_average,vote_count,overview
0,278,The Shawshank Redemption,1994-09-23,42.1605,8.717,29992,Imprisoned in the 1940s for the double murder ...
1,238,The Godfather,1972-03-14,36.5278,8.687,22658,"Spanning the years 1945 to 1955, a chronicle o..."
2,240,The Godfather Part II,1974-12-20,25.5386,8.572,13720,In the continuing saga of the Corleone crime f...
3,424,Schindler's List,1993-12-15,23.5837,8.567,17246,The true story of how businessman Oskar Schind...
4,389,12 Angry Men,1957-04-10,19.3006,8.556,9844,The defense and the prosecution have rested an...
...,...,...,...,...,...,...,...
9995,9796,Turistas,2006-12-01,2.7055,5.471,879,A group of young backpackers' vacation turns s...
9996,253310,Premature,2014-07-02,2.7309,5.473,478,"On the most important day of his young life, a..."
9997,87368,17 Girls,2011-06-13,0.5833,5.500,327,"When Camille accidentally becomes pregnant, sh..."
9998,1063422,The Strays,2023-02-17,2.0145,5.500,399,A Black woman's meticulously crafted life of p...
9999,75198,Welcome Aboard,2011-10-05,1.2395,5.500,540,"Isabelle, HR of a large cruise company, made t..."

In [41]:
df_movie.to_csv("df_movie.csv")