In [68]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/onidzelskyi/chat-messages/messages.csv
/kaggle/input/datasets/divjotbedi/order-dataset/order.csv

In [5]:
date=pd.read_csv("/kaggle/input/datasets/divjotbedi/order-dataset/order.csv")

In [6]:
date.head()

         date  product_id  city_id  orders
0  2019-10-17        2824       25       3
1  2018-09-08        4657       14       1
2  2019-11-24        9935       25      50
3  2019-03-09        1520       25       1
4  2018-08-12        4811       41      50

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        100 non-null    object
 1   product_id  100 non-null    int64
 2   city_id     100 non-null    int64
 3   orders      100 non-null    int64
dtypes: int64(3), object(1)
memory usage: 3.3+ KB

In [8]:
date['date'] = pd.to_datetime(date['date'])

In [12]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        100 non-null    datetime64[ns]
 1   product_id  100 non-null    int64
 2   city_id     100 non-null    int64
 3   orders      100 non-null    int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 3.3 KB

In [17]:
date['date_year']=date['date'].dt.year
date['date_month']=date['date'].dt.month_name()
date['date_day']=date['date'].dt.day

In [18]:
date.head()

        date  product_id  city_id  orders  date_year date_month  date_day
0 2019-10-17        2824       25       3       2019    October        17
1 2018-09-08        4657       14       1       2018  September         8
2 2019-11-24        9935       25      50       2019   November        24
3 2019-03-09        1520       25       1       2019      March         9
4 2018-08-12        4811       41      50       2018     August        12

In [22]:
date['date_DOW']=date['date'].dt.dayofweek
date['date_DOW_name']=date['date'].dt.day_name()

In [23]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_day,date_DOW,date_DOW_name
0,2019-10-17,2824,25,3,2019,October,17,3,Thursday
1,2018-09-08,4657,14,1,2018,September,8,5,Saturday
2,2019-11-24,9935,25,50,2019,November,24,6,Sunday
3,2019-03-09,1520,25,1,2019,March,9,5,Saturday
4,2018-08-12,4811,41,50,2018,August,12,6,Sunday

In [26]:
date['date_Is_weekend']=np.where(date['date_DOW_name'].isin(['Saturday','Sunday']),1,0)

In [27]:
date.head(10)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_DOW,date_DOW_name,date_Is_weekend
0,2019-10-17,2824,25,3,2019,October,17,3,Thursday,0
1,2018-09-08,4657,14,1,2018,September,8,5,Saturday,1
2,2019-11-24,9935,25,50,2019,November,24,6,Sunday,1
3,2019-03-09,1520,25,1,2019,March,9,5,Saturday,1
4,2018-08-12,4811,41,50,2018,August,12,6,Sunday,1
5,2018-01-28,4257,19,20,2018,January,28,6,Sunday,1
6,2019-03-06,4611,33,50,2019,March,6,2,Wednesday,0
7,2018-10-12,1106,8,1,2018,October,12,4,Friday,0
8,2019-12-16,7924,7,3,2019,December,16,0,Monday,0
9,2018-06-09,4527,8,5,2018,June,9,5,Saturday,1

In [38]:
date=date.drop(columns=['product_id','city_id','orders'])

In [40]:
date=date.drop(columns=['date_week'])

In [41]:
date.head()

,date,date_year,date_month,date_day,date_DOW,date_DOW_name,date_Is_weekend
0,2019-10-17,2019,October,17,3,Thursday,0
1,2018-09-08,2018,September,8,5,Saturday,1
2,2019-11-24,2019,November,24,6,Sunday,1
3,2019-03-09,2019,March,9,5,Saturday,1
4,2018-08-12,2018,August,12,6,Sunday,1

In [42]:
date['quarter']=date['date'].dt.quarter

In [43]:
date.head()

,date,date_year,date_month,date_day,date_DOW,date_DOW_name,date_Is_weekend,quarter
0,2019-10-17,2019,October,17,3,Thursday,0,4
1,2018-09-08,2018,September,8,5,Saturday,1,3
2,2019-11-24,2019,November,24,6,Sunday,1,4
3,2019-03-09,2019,March,9,5,Saturday,1,1
4,2018-08-12,2018,August,12,6,Sunday,1,3

In [47]:
date['semester']=np.where(date['quarter'].isin([3,4]),2,1)

In [48]:
date.head()

,date,date_year,date_month,date_day,date_DOW,date_DOW_name,date_Is_weekend,quarter,semester
0,2019-10-17,2019,October,17,3,Thursday,0,4,2
1,2018-09-08,2018,September,8,5,Saturday,1,3,2
2,2019-11-24,2019,November,24,6,Sunday,1,4,2
3,2019-03-09,2019,March,9,5,Saturday,1,1,1
4,2018-08-12,2018,August,12,6,Sunday,1,3,2

In [72]:
import datetime

In [73]:
today=datetime.datetime.today()

In [74]:
today

datetime.datetime(2026, 7, 4, 10, 0, 26, 336081)

In [52]:
today-date['date']

0    2452 days 09:47:35.250298
1    2856 days 09:47:35.250298
2    2414 days 09:47:35.250298
3    2674 days 09:47:35.250298
4    2883 days 09:47:35.250298
                ...
95   2540 days 09:47:35.250298
96   2487 days 09:47:35.250298
97   2898 days 09:47:35.250298
98   2849 days 09:47:35.250298
99   2823 days 09:47:35.250298
Name: date, Length: 100, dtype: timedelta64[ns]

In [55]:
(today-date['date']).dt.days

0     2452
1     2856
2     2414
3     2674
4     2883
      ...
95    2540
96    2487
97    2898
98    2849
99    2823
Name: date, Length: 100, dtype: int64

In [61]:
np.round((today-date['date']) / np.timedelta64(1,'W'),0)

0     350.0
1     408.0
2     345.0
3     382.0
4     412.0
      ...
95    363.0
96    355.0
97    414.0
98    407.0
99    403.0
Name: date, Length: 100, dtype: float64

In [62]:
date['date_week'] = date['date'].dt.isocalendar().week

In [63]:
date.head()

,date,date_year,date_month,date_day,date_DOW,date_DOW_name,date_Is_weekend,quarter,semester,date_week
0,2019-10-17,2019,October,17,3,Thursday,0,4,2,42
1,2018-09-08,2018,September,8,5,Saturday,1,3,2,36
2,2019-11-24,2019,November,24,6,Sunday,1,4,2,47
3,2019-03-09,2019,March,9,5,Saturday,1,1,1,10
4,2018-08-12,2018,August,12,6,Sunday,1,3,2,32

In [64]:
np.round((today-date['date']) /np.timedelta64(1,'D')/30,0)

0     82.0
1     95.0
2     80.0
3     89.0
4     96.0
      ...
95    85.0
96    83.0
97    97.0
98    95.0
99    94.0
Name: date, Length: 100, dtype: float64

In [70]:
time=pd.read_csv("/kaggle/input/datasets/onidzelskyi/chat-messages/messages.csv")

In [71]:
time.head()

                  date                                                msg
0  2012-01-02 00:21:00                            нужен парень 0965188229
1  2012-01-02 00:24:00                       Всем привет! Как настроение?
2  2012-01-02 00:27:00  ИЩЮ ВТОРУЮ ПОЛОВИНКУ МНЕ 23 ЗОВУТ ВАНЯ ПИШИТЕ ...
3  2012-01-02 00:27:00     Эля  встречала в шумной компании! Все отлично!
4  2012-01-02 00:27:00  Парень катается по городу. Нужна девушка. 0992...

In [79]:
time['date']=pd.to_datetime(time['date'])

In [81]:
time['hours']=time['date'].dt.hour

In [82]:
time['mins']=time['date'].dt.minute

In [84]:
time['secs']=time['date'].dt.second

In [85]:
time['time']=time['date'].dt.time

In [88]:
time.sample(10)

,date,msg,hours,mins,secs,time
470622,2012-08-08 23:39:00,Я парень ищу девушку 0636084776. Настя как де...,23,39,0,23:39:00
678676,2013-08-21 23:07:00,Женщина порой изменяет не потому что в ней мн...,23,7,0,23:07:00
291693,2015-05-20 00:52:00,Парень ищет девушку для и/о встречи Запорожье ...,0,52,0,00:52:00
1104403,2016-04-08 23:16:00,М Мужчина пригласит Женщ на Шампанское Дн-жи...,23,16,0,23:16:00
626254,2013-06-12 00:16:00,уж замуж невтерпеж! кто возьмет? Екатерина 25...,0,16,0,00:16:00
1015042,2015-06-10 23:31:00,девченки кому скучно звоните 063-720-05-79 Днепр,23,31,0,23:31:00
827013,2014-03-15 00:53:00,2 симпотичных парня пригласят девочек на роман...,0,53,0,00:53:00
184973,2014-01-22 01:31:00,.П. 28л Познакомлюсь с .Девушкой.от 25 до 30 л...,1,31,0,01:31:00
847971,2014-04-30 00:14:00,п+п до 30 смс 0952903601,0,14,0,00:14:00
807996,2014-02-03 22:34:00,д25л з днепр обл. Ищю п с.о есть ребенак не с...,22,34,0,22:34:00

In [89]:
today-time['date']

0         5297 days 09:39:26.336081
1         5297 days 09:36:26.336081
2         5297 days 09:33:26.336081
3         5297 days 09:33:26.336081
4         5297 days 09:33:26.336081
                     ...
1147095   3440 days 09:38:26.336081
1147096   3440 days 09:38:26.336081
1147097   3440 days 09:38:26.336081
1147098   3440 days 09:36:26.336081
1147099   3440 days 09:34:26.336081
Name: date, Length: 1147100, dtype: timedelta64[ns]

In [92]:
(today-time['date']).dt.days

0          5297
1          5297
2          5297
3          5297
4          5297
           ...
1147095    3440
1147096    3440
1147097    3440
1147098    3440
1147099    3440
Name: date, Length: 1147100, dtype: int64

In [94]:
np.round((today-time['date']) / np.timedelta64(1,'m'),0)

0          7628259.0
1          7628256.0
2          7628253.0
3          7628253.0
4          7628253.0
             ...
1147095    4954178.0
1147096    4954178.0
1147097    4954178.0
1147098    4954176.0
1147099    4954174.0
Name: date, Length: 1147100, dtype: float64

In [95]:
np.round((today-time['date']) / np.timedelta64(1,'s'),0)

0          457695566.0
1          457695386.0
2          457695206.0
3          457695206.0
4          457695206.0
              ...
1147095    297250706.0
1147096    297250706.0
1147097    297250706.0
1147098    297250586.0
1147099    297250466.0
Name: date, Length: 1147100, dtype: float64

In [96]:
np.round((today-time['date']) / np.timedelta64(1,'h'),0)

0          127138.0
1          127138.0
2          127138.0
3          127138.0
4          127138.0
             ...
1147095     82570.0
1147096     82570.0
1147097     82570.0
1147098     82570.0
1147099     82570.0
Name: date, Length: 1147100, dtype: float64

In [97]:
np.round((today-time['date']) / np.timedelta64(1,'ms'),0)

0          4.576956e+11
1          4.576954e+11
2          4.576952e+11
3          4.576952e+11
4          4.576952e+11
               ...
1147095    2.972507e+11
1147096    2.972507e+11
1147097    2.972507e+11
1147098    2.972506e+11
1147099    2.972505e+11
Name: date, Length: 1147100, dtype: float64